---
abstract: 'HTTP/1.1 UserAgent using AnyEvent'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-UA
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 5
  HTTP::Easy: 0
  Scalar::Util: 0
  common::sense: 2
version: 0.01_01
